# -*- coding: utf-8 -*-
"""Test.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wBDJ9FhHOrUoiI_kXL0xQW7ih3QfJfCs
"""

#Test.py

def printTest():
  print('This is a test message')